# Generated by Django 5.2.3 on 2025-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_dec', models.CharField(max_length=500)),
                ('recipe_rating', models.IntegerField(max_length=5)),
                ('recipe_direcions', models.CharField(max_length=500)),
                ('recipe_ingredients', models.CharField(help_text="enter valu split by ',' ex: <b>nutrisionals yeats ,soya sauce</b>", max_length=500)),
            ],
        ),
    ]
