# Generated by Django 5.2.3 on 2025-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeslist',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='RecipeImages'),
        ),
    ]
