# Generated by Django 5.2.3 on 2025-07-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeslist_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('recipe_name', models.CharField(max_length=500)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='RecipeRequestImages')),
            ],
        ),
    ]
