# Generated by Django 5.2.11 on 2026-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_reciperequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_ingredients',
            field=models.CharField(help_text="enter value split by ',' ex: <b>nutritional yeast, soya sauce</b>", max_length=500),
        ),
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_rating',
            field=models.IntegerField(),
        ),
    ]
