# Generated by Django 5.2.4 on 2026-02-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeslist_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeslist',
            name='calories',
            field=models.IntegerField(default=0, help_text='Calories per serving'),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='carbs',
            field=models.FloatField(default=0, help_text='Carbohydrates in grams'),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='cooking_time',
            field=models.CharField(default='30 mins', help_text='e.g., 15 mins, 30-40 mins, 1 hour', max_length=50),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='cuisine_type',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Thai', 'Thai'), ('Continental', 'Continental'), ('Gujarati', 'Gujarati'), ('Kathiyawadi', 'Kathiyawadi'), ('Punjabi', 'Punjabi'), ('South Indian', 'South Indian'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Other', 'Other')], default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='fat',
            field=models.FloatField(default=0, help_text='Fat in grams'),
        ),
        migrations.AddField(
            model_name='recipeslist',
            name='protein',
            field=models.FloatField(default=0, help_text='Protein in grams'),
        ),
    ]
