# Generated by Django 4.2.29 on 2026-03-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeslist_calories_recipeslist_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_direcions',
            field=models.TextField(help_text="Enter each direction separated by '|' ex: <b>Boil the water | Add the pasta | Cook for 10 minutes</b>"),
        ),
        migrations.AlterField(
            model_name='recipeslist',
            name='recipe_ingredients',
            field=models.TextField(help_text="enter value split by ',' ex: <b>nutritional yeast, soya sauce</b>"),
        ),
    ]
